version: 2
updates:
  # Dockerイメージの更新チェック (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Pythonパッケージの更新チェック (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Gitサブモジュールの更新チェック
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions ワークフロー自体の更新チェック
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
